name: "openair_nature_dbt"
version: "1.0.0"
config-version: 2

profile: "openair_profile"

model-paths: ["models"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  openair_nature_dbt:
    materialized: table
